name: daiku-app build

on:
  push:
    paths:
      - ".github/workflows/**"
      - "daiku-app/**"
      - "daiku-domain/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
        cache: 'gradle'

    - name: AWS Production ENV
      if: contains(toJSON(github.ref), 'master')
      run: |
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_PRD }} >> $GITHUB_ENV
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_PRD}} >> $GITHUB_ENV
        echo TF_VAR_ENV=prd >> $GITHUB_ENV
        echo AWS_ECS_TASK_BATCH_DEFINITION_BASE64=${{ secrets.AWS_ECS_TASK_BATCH_DEFINITION_BASE64_PRD }} >> $GITHUB_ENV
        echo AWS_ECS_TASK_DEFINITION_BASE64=${{ secrets.AWS_ECS_TASK_DEFINITION_BASE64_PRD }} >> $GITHUB_ENV
        echo AWS_ECS_SERVICE=${{ secrets.AWS_ECS_SERVICE_PRD }} >> $GITHUB_ENV
        echo AWS_ECS_SERVICE_BATCH=${{ secrets.AWS_ECS_SERVICE_BATCH_PRD }} >> $GITHUB_ENV
        echo AWS_ECS_CLUSTER=${{ secrets.AWS_ECS_CLUSTER_PRD }} >> $GITHUB_ENV
        echo AWS_ECS_CONTAINER_NAME=${{ secrets.AWS_ECS_CONTAINER_NAME_PRD }} >> $GITHUB_ENV

    - name: AWS Develop ENV
      if: contains(toJSON(github.ref), 'develop') || contains(toJSON(github.ref), 'feature') || github.event_name == 'pull_request'
      run: |
        echo AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_DEV }} >> $GITHUB_ENV
        echo AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_DEV}} >> $GITHUB_ENV
        echo TF_VAR_ENV=dev >> $GITHUB_ENV
        echo AWS_ECS_TASK_DEFINITION_BASE64=${{ secrets.AWS_ECS_TASK_DEFINITION_BASE64_DEV }} >> $GITHUB_ENV
        echo AWS_ECS_TASK_BATCH_DEFINITION_BASE64=${{ secrets.AWS_ECS_TASK_BATCH_DEFINITION_BASE64_DEV }} >> $GITHUB_ENV
        echo AWS_ECS_SERVICE=${{ secrets.AWS_ECS_SERVICE_DEV }} >> $GITHUB_ENV
        echo AWS_ECS_SERVICE_BATCH=${{ secrets.AWS_ECS_SERVICE_BATCH_DEV }} >> $GITHUB_ENV
        echo AWS_ECS_CLUSTER=${{ secrets.AWS_ECS_CLUSTER_DEV }} >> $GITHUB_ENV
        echo AWS_ECS_CONTAINER_NAME=${{ secrets.AWS_ECS_CONTAINER_NAME_DEV }} >> $GITHUB_ENV

    - name: Configure AWS credentials
      id: aws-credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ env.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ env.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle app package build
      id: build-gradle
      run: |
        ./gradlew :daiku-app:build
        ./gradlew :daiku-app:bootBuildImage --imageName=springio/${{ env.TF_VAR_ENV }}/daiku-app-docker:latest
        ./gradlew :daiku-batch:build
        ./gradlew :daiku-app:bootBuildImage --imageName=springio/${{ env.TF_VAR_ENV }}/daiku-batch-docker:latest

    - name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      if: always() # always run even if the previous step fails
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'

    - name: Login to Amazon ECR
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: ecr push app
      id: build-image
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY_APP: ${{ env.TF_VAR_ENV }}/daiku-app
        ECR_REPOSITORY_BATCH: ${{ env.TF_VAR_ENV }}/daiku-batch
        AWS_ACCOUNT_ID: ${{ steps.aws-credentials.outputs.aws-account-id }}
        IMAGE_TAG: latest
      run: |
        docker tag springio/${{ env.TF_VAR_ENV }}/daiku-app-docker:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY_APP }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY_APP }}
        docker tag springio/${{ env.TF_VAR_ENV }}/daiku-batch-docker:latest ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY_BATCH }}:${{ env.IMAGE_TAG }}
        docker push ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.ap-northeast-1.amazonaws.com/${{ env.ECR_REPOSITORY_BATCH }}
        echo "::set-output name=image::$ECR_REGISTRY/$ECR_REPOSITORY_APP:$IMAGE_TAG"
        echo "::set-output name=image-batch::$ECR_REGISTRY/$ECR_REPOSITORY_BATCH:$IMAGE_TAG"

    - name: Create task-definition.json file from base64
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      run: |
        if [[ -n "${{ env.AWS_ECS_TASK_DEFINITION_BASE64 }}" ]]; then
          echo "${{ env.AWS_ECS_TASK_DEFINITION_BASE64 }}" | base64 -d > ./task-definition.json
        fi
        if [[ -n "${{ env.AWS_ECS_TASK_BATCH_DEFINITION_BASE64 }}" ]]; then
          echo "${{ env.AWS_ECS_TASK_BATCH_DEFINITION_BASE64 }}" | base64 -d > ./task-definition-batch.json
        fi

    - name: Deploy to Amazon ECS
      id: task-def
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./task-definition.json
        container-name: ${{ env.AWS_ECS_CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy to Amazon ECS
      id: task-batch-def
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ./task-definition-batch.json
        image: ${{ steps.build-image.outputs.image-batch }}

    - name: Deploy Amazon ECS task definition
      id: app-deploy
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.AWS_ECS_SERVICE }}
        cluster: ${{ env.AWS_ECS_CLUSTER }}
        wait-for-service-stability: true

    - name: Deploy Amazon ECS task definition
      id: batch-deploy
      if: (github.ref == 'refs/heads/master' ||  github.ref == 'refs/heads/develop') && github.event_name == 'push'
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-batch-def.outputs.task-definition }}
        service: ${{ env.AWS_ECS_SERVICE_BATCH }}
        cluster: ${{ env.AWS_ECS_CLUSTER }}
        wait-for-service-stability: true